controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

product_index:
    path: /products
    controller: App\Controller\ProductController::index
import:
    path: /import
    controller: App\Controller\ImportController::import